"""add ministers column"""

from alembic import op
import sqlalchemy as sa

revision = "20250222_0007"
down_revision = "20250213_0006"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('ministers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'ministers')
    # ### end Alembic commands ###
